services:
  - type: web
    name: bnb-fly-proxy
    env: docker
    region: singapore
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: PROXY_API_KEY
        sync: false
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: TIMEZONE_OFFSET_HOURS
        value: 8
